Feature/011 front end dummy
BeePong/42_transcendence pull request #25
Opened 2024-07-12 18:33 UTC by wengcychan

Close #11

@pixelsnow @liocle @djames9 

I have implemented routing for single page application. The registration, login and logout should be working now.

Run make and open https://localhost/

The codespace is not working because CSRF_TRUSTED_ORIGINS is set to https://localhost only

2024-07-13 12:38 UTC, linhtng commented on srcs/frontend/js/route.js
> +	const page = routes[route] || window.location.pathname.slice(1);
check if you can pass the path directly

2024-07-13 12:47 UTC, linhtng commented on srcs/backend/accounts/urls.py
> +    path('', include('django.contrib.auth.urls')),
See how to properly having custom login logout without having default auth url
i.e. remove this line

2024-07-13 12:49 UTC, pixelsnow requested changes
reviewed together, suggested some improvements

2024-07-15 10:41 UTC, linhtng approved these changes
Routing for single page application is there.
Register, login, logout kinda works. However, register and login is not working properly when you input invalid info in the form. It does nothing, while the default function of register and login are informative and telling you exactly what's wrong.
But I guess it is not the main purpose of this ticket, so approving for the routing part. The work on register and login will continue in ticket
https://github.com/BeePong/42_transcendence/issues/17#issue-2393698472
I guess.

2024-07-15 18:10 UTC, wengcychan commented
@pixelsnow Please also add the error message in the Figma and I will include it in #17 

> Routing for single page application is there. Register, login, logout kinda works. However, register and login is not working properly when you input invalid info in the form. It does nothing, while the default function of register and login are informative and telling you exactly what's wrong. But I guess it is not the main purpose of this ticket, so approving for the routing part. The work on register and login will continue in ticket [#17 (comment)](https://github.com/BeePong/42_transcendence/issues/17#issue-2393698472) I guess.

2024-07-18 12:32 UTC, pixelsnow approved these changes
Corrections look good, approved

2024-07-18 14:33 UTC, merged