40 refactor models form tournament
BeePong/42_transcendence pull request #54
Opened 2024-08-17 12:35 UTC by djames9

This pull request introduces the following features and improvements:

Django Admin Integration: 
Added Django Admin to the project, allowing for easy management of models through the admin interface.
Database Population: 
Implemented scripts and/or Django management commands to populate the database with initial data.
Data Fetching:
Added views and logic to fetch data from the database and display it within the application.

Changes Made

1. Django Admin Integration:
   - Registered the relevant models in `admin.py` to make them manageable via the Django Admin interface.
   - Configured Django settings to enable admin access.

2. Database Population:
   - Created scripts or management commands to seed the database with initial data.
   - Ensured that the data is consistent and matches the application's requirements.

3. Data Fetching:
   - Added new views to query the database and render the fetched data in templates or return it via APIs.
   - Ensured the views are optimized and properly tested.

4. Migrations:
   - Generated and applied the necessary migrations to reflect model changes in the database.

How to Access the Django Admin Interface

1. Run the Django Development Server:
   Ensure the development server is running by using the command:

Django docker using  make exec_backend
Write python manage.py createsuperuser
 go to http://127.0.0.1:8000/admin/
 and use your superuser logs to see all the databases and see what happen if it change

2024-08-17 16:14 UTC, liocle approved these changes
Looks good to me and thanks for the live review.

2024-08-17 17:03 UTC, linhtng requested changes

2024-08-17 17:03 UTC, linhtng commented on srcs/nginx/nginx.conf
> +    location /static/ {
@djames9  what are these for?
```
location /static/ {
        alias /path/to/your/static/files/;
    }

    # Serve media files (adjust the path to your media files)
    location /media/ {
        alias /path/to/your/media/files/;
    }
```

2024-08-19 13:57 UTC, linhtng approved these changes
LGTM. Approve.

2024-08-19 13:57 UTC, merged